services:
  - type: web
    name: recipe-site
    env: static
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    routes:
      - type: rewrite
        source: '.*'
        destination: /index.html
